apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-http-gw
  namespace: default
spec:
  selector:
    app: istio-ingressgateway # Ingress-Gateway
  servers:
    - port:
        number: 80
        name: httpd-http
        protocol: HTTP
      hosts:
        - "*"

