apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-vs
spec:
  hosts:
  - "*"
  gateways:
  - my-http-gw
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: httpd
        port:
          number: 80