apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd
  name: httpd
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-v1
  creationTimestamp: null
  labels:
    app: httpd
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd
        version: v1
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-v2
  creationTimestamp: null
  labels:
    app: httpd
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd
        version: v2
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
status: {}

